name: nasqar_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base==4.2.2 
  - r-shiny
  - bioconductor-clusterprofiler
  - r-dt
  - r-shinydashboard
  - r-shinyjs
  - r-shinyBS
  - r-shinycssloaders
